spring.application.name=orgconnect

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/orgconnect
spring.datasource.username=root
spring.datasource.password=Pigpork@2123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.data.mongodb.uri=mongodb://localhost:27017/orgconnect
spring.data.mongodb.database=orgconnect


